{
  "openapi": "3.0.1",
  "info": {
    "description": "This is Video Management System App",
    "version": "1.0.5",
    "title": "Video Management System",
    "contact": {
      "email": "nitish.kumar@indusnet.co.in"
    }
  },
  "tags": [
    {
      "name": "Users",
      "description": "All User Access"
    },
    {
      "name": "Admin",
      "description": "Only Admin Access"
    }
  ],

  "paths": {},
  "components": {
    "schemas": {
      "serverErrorResponse": {
        "title": "Server Error Response",
        "type": "object",
        "properties": {
          "status": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          },
          "error": {
            "type": "string"
          }
        },
        "example": {
          "status": 500,
          "message": "Something Went Wrong",
          "error": "Error"
        }
      },
      "badRequestResponse": {
        "title": "Bad Request Response",
        "type": "object",
        "properties": {
          "status": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          },
          "validationErrors": {
            "type": "string"
          }
        },
        "example": {
          "status": 400,
          "message": "Something Went Wrong",
          "validationErrors": "Error"
        }
      },
      "forbiddenResponse": {
        "title": "Forbidden Response",
        "type": "object",
        "properties": {
          "status": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          }
        },
        "example": {
          "status": 403,
          "message": "Forbidden"
        }
      },
      "noDataResponseObject": {
        "title": "No Data Object Response",
        "type": "object",
        "properties": {
          "status": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {}
          }
        },
        "example": {
          "status": 204,
          "message": "No Data Found",
          "data": {}
        }
      },
      "createSuccessResponseObject": {
        "title": "Create Success Response",
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "status": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "user": {
                "$ref": "#/components/schemas/user"
              }
            }
          }
        },
        "example": {
          "success": true,
          "status": 201,
          "message": "Created Successfully",
          "data": {
            "first_name": "Riyaz_2",
            "last_name": "Ahmad_2",
            "password": "Riyaz@8800",
            "email": "riyaz.ahmad@indusnet.co.in"
          }
        }
      },
      "successResponseObject": {
        "title": "Success Response",
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "status": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "user": {
                "$ref": "#/components/schemas/user"
              }
            }
          }
        },
        "example": {
          "success": true,
          "status": 200,
          "message": "Successful",
          "data": {}
        }
      },
      "successResponseObjectForSendMail": {
        "title": "Success Response",
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "status": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          }
        },
        "example": {
          "success": true,
          "status": 200,
          "message": "Successfully Sent Mail"
        }
      },
      "loginResponseObject": {
        "title": "Login Success Response",
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "status": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "tokens": {
                "type": "object",
                "properties": {
                  "Access token": {
                    "type": "string"
                  },
                  "Access Token Expiry": {
                    "type": "string"
                  },
                  "Refresh Token": {
                    "type": "string"
                  },
                  "Refresh Token Expiry": {
                    "type": "string"
                  }
                }
              },
              "user": {
                "$ref": "#/components/schemas/user"
              }
            }
          }
        },
        "example": {
          "success": true,
          "status": 200,
          "message": "Login Successfully",
          "data": {
            "email": "nk880093@gmail.com",
            "password": "Niku@8800"
          }
        }
      },
      "logoutResponseObject": {
        "title": "Log Out Success Response",
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "status": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          }
        },
        "example": {
          "success": true,
          "status": 200,
          "message": "Log Out Successfully",
          "data": {}
        }
      },
      "user": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "integer"
          },
          "first_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "isAdmin": {
            "type": "string"
          },
          "verified": {
            "type": "boolean"
          },
          "email": {
            "type": "string"
          }
        }
      }
    }
  }
}
